name: covidtrends_age
channels:
  - conda-forge
  - defaults
dependencies:
  - argon2-cffi=20.1.0
  - async_generator=1.10
  - attrs=20.2.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.1
  - blas=1.0
  - bleach=3.2.1
  - brotlipy=0.7.0
  - ca-certificates=2020.6.20
  - certifi=2020.6.20
  - cffi=1.14.3
  - click=7.1.2
  - colorama=0.4.3
  - cycler=0.10.0
  - dash=1.16.1
  - dash-core-components=1.12.1
  - dash-html-components=1.1.1
  - dash-renderer=1.8.1
  - dash-table=4.10.1
  - decorator=4.4.2
  - defusedxml=0.6.0
  - entrypoints=0.3
  - flask=1.1.2
  - flask-compress=1.5.0
  - freetype=2.10.2
  - future=0.18.2
  - icc_rt=2019.0.0
  - icu=67.1
  - importlib-metadata=1.7.0
  - importlib_metadata=1.7.0
  - intel-openmp=2020.1
  - ipykernel=5.3.4
  - ipython=7.18.1
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - itsdangerous=1.1.0
  - jedi=0.15.2
  - jinja2=2.11.2
  - joblib=0.16.0
  - jpeg=9d
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=6.1.7
  - jupyter_console=6.2.0
  - jupyter_core=4.6.3
  - jupyterlab_pygments=0.1.1
  - kiwisolver=1.2.0
  - libblas=3.8.0
  - libcblas=3.8.0
  - libclang=10.0.1
  - liblapack=3.8.0
  - libpng=1.6.37
  - libsodium=1.0.17
  - libtiff=4.1.0
  - lz4-c=1.9.2
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markupsafe=1.1.1
  - matplotlib=3.3.2
  - matplotlib-base=3.3.2
  - mistune=0.8.4
  - mkl=2020.1
  - mkl-service=2.3.0
  - msys2-conda-epoch=20160418
  - nbclient=0.5.0
  - nbconvert=6.0.4
  - nbformat=5.0.7
  - nest-asyncio=1.4.0
  - notebook=6.1.4
  - numpy=1.19.1
  - olefile=0.46
  - openssl=1.1.1g
  - packaging=20.4
  - pandas=1.1.2
  - pandoc=2.10.1
  - pandocfilters=1.4.2
  - parso=0.5.2
  - pickleshare=0.7.5
  - pillow=7.2.0
  - pip=20.2.3
  - plotly=4.10.0
  - prometheus_client=0.8.0
  - prompt-toolkit=3.0.7
  - prompt_toolkit=3.0.7
  - pycparser=2.20
  - pygments=2.7.1
  - pyparsing=2.4.7
  - pyqt=5.12.3
  - pyrsistent=0.17.3
  - python=3.8.3
  - python-dateutil=2.8.1
  - python_abi=3.8
  - pytz=2020.1
  - pywin32=227
  - pywinpty=0.5.7
  - pyyaml=5.3.1
  - pyzmq=19.0.2
  - qt=5.12.6
  - qtconsole=4.7.7
  - qtpy=1.9.0
  - retrying=1.3.3
  - scikit-learn=0.23.2
  - scipy=1.5.0
  - send2trash=1.5.0
  - setuptools=49.6.0
  - six=1.15.0
  - sqlite=3.33.0
  - terminado=0.8.3
  - testpath=0.4.4
  - threadpoolctl=2.1.0
  - tk=8.6.10
  - tornado=6.0.4
  - traitlets=5.0.4
  - vc=14.1
  - vs2015_runtime=14.16.27012
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - werkzeug=1.0.1
  - wheel=0.35.1
  - widgetsnbextension=3.5.1
  - wincertstore=0.2
  - winpty=0.4.3
  - xz=5.2.5
  - yaml=0.2.5
  - zeromq=4.3.2
  - zipp=3.1.0
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
    - pyqt5-sip==4.19.18
    - pyqtwebengine==5.12.1
